/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.wits.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Connector service. Represents a row in the &quot;AppConnectorNS_Connector&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.wits.portal.model.impl.ConnectorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.wits.portal.model.impl.ConnectorImpl}.
 * </p>
 *
 * @author Administrator
 * @see Connector
 * @see com.wits.portal.model.impl.ConnectorImpl
 * @see com.wits.portal.model.impl.ConnectorModelImpl
 * @generated
 */
public interface ConnectorModel extends BaseModel<Connector>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a connector model instance should use the {@link Connector} interface instead.
	 */

	/**
	 * Returns the primary key of this connector.
	 *
	 * @return the primary key of this connector
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this connector.
	 *
	 * @param primaryKey the primary key of this connector
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the connector ID of this connector.
	 *
	 * @return the connector ID of this connector
	 */
	public long getConnectorId();

	/**
	 * Sets the connector ID of this connector.
	 *
	 * @param connectorId the connector ID of this connector
	 */
	public void setConnectorId(long connectorId);

	/**
	 * Returns the group ID of this connector.
	 *
	 * @return the group ID of this connector
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this connector.
	 *
	 * @param groupId the group ID of this connector
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this connector.
	 *
	 * @return the company ID of this connector
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this connector.
	 *
	 * @param companyId the company ID of this connector
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this connector.
	 *
	 * @return the user ID of this connector
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this connector.
	 *
	 * @param userId the user ID of this connector
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this connector.
	 *
	 * @return the user uuid of this connector
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this connector.
	 *
	 * @param userUuid the user uuid of this connector
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this connector.
	 *
	 * @return the user name of this connector
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this connector.
	 *
	 * @param userName the user name of this connector
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this connector.
	 *
	 * @return the create date of this connector
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this connector.
	 *
	 * @param createDate the create date of this connector
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this connector.
	 *
	 * @return the modified date of this connector
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this connector.
	 *
	 * @param modifiedDate the modified date of this connector
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the comany name of this connector.
	 *
	 * @return the comany name of this connector
	 */
	@AutoEscape
	public String getComanyName();

	/**
	 * Sets the comany name of this connector.
	 *
	 * @param comanyName the comany name of this connector
	 */
	public void setComanyName(String comanyName);

	/**
	 * Returns the type of this connector.
	 *
	 * @return the type of this connector
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this connector.
	 *
	 * @param type the type of this connector
	 */
	public void setType(String type);

	/**
	 * Returns the name of this connector.
	 *
	 * @return the name of this connector
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this connector.
	 *
	 * @param name the name of this connector
	 */
	public void setName(String name);

	/**
	 * Returns the version code of this connector.
	 *
	 * @return the version code of this connector
	 */
	@AutoEscape
	public String getVersionCode();

	/**
	 * Sets the version code of this connector.
	 *
	 * @param versionCode the version code of this connector
	 */
	public void setVersionCode(String versionCode);

	/**
	 * Returns the version name of this connector.
	 *
	 * @return the version name of this connector
	 */
	@AutoEscape
	public String getVersionName();

	/**
	 * Sets the version name of this connector.
	 *
	 * @param versionName the version name of this connector
	 */
	public void setVersionName(String versionName);

	/**
	 * Returns the url of this connector.
	 *
	 * @return the url of this connector
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this connector.
	 *
	 * @param url the url of this connector
	 */
	public void setUrl(String url);

	/**
	 * Returns the status of this connector.
	 *
	 * @return the status of this connector
	 */
	public int getStatus();

	/**
	 * Sets the status of this connector.
	 *
	 * @param status the status of this connector
	 */
	public void setStatus(int status);

	/**
	 * Returns the update log of this connector.
	 *
	 * @return the update log of this connector
	 */
	@AutoEscape
	public String getUpdateLog();

	/**
	 * Sets the update log of this connector.
	 *
	 * @param updateLog the update log of this connector
	 */
	public void setUpdateLog(String updateLog);

	/**
	 * Returns the remark of this connector.
	 *
	 * @return the remark of this connector
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this connector.
	 *
	 * @param remark the remark of this connector
	 */
	public void setRemark(String remark);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Connector connector);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Connector> toCacheModel();

	@Override
	public Connector toEscapedModel();

	@Override
	public Connector toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}